services:
  mysql:
    image: mysql:latest
    container_name: test_sql_server
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: day2
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
